apiVersion: apps/v1
kind: Deployment
metadata:
  name: wardis-nats
  namespace: wardis
  labels:
    app: wardis-nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wardis-nats
  template:
    metadata:
      labels:
        app: wardis-nats
    spec:
      containers:
        - name: nats
          image: nats:2.10-alpine
          ports:
            - containerPort: 4222
              name: client
            - containerPort: 8222
              name: monitor
          livenessProbe:
            httpGet:
              path: /varz
              port: 8222
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /varz
              port: 8222
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: wardis-nats-svc
  namespace: wardis
  labels:
    app: wardis-nats
spec:
  ports:
    - port: 4222
      targetPort: 4222
      name: client
    - port: 8222
      targetPort: 8222
      name: monitor
  selector:
    app: wardis-nats
  type: ClusterIP
