-- Up Migration

ALTER TABLE cameras ADD COLUMN IF NOT EXISTS ip VARCHAR(50);
ALTER TABLE cameras ADD COLUMN IF NOT EXISTS port INTEGER;
ALTER TABLE cameras ADD COLUMN IF NOT EXISTS username VARCHAR(100);
ALTER TABLE cameras ADD COLUMN IF NOT EXISTS password_encrypted VARCHAR(255);
ALTER TABLE cameras ADD COLUMN IF NOT EXISTS ptz_supported BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE cameras ADD COLUMN IF NOT EXISTS profile_token VARCHAR(100);
